# Branch definition: only build master and PRs
branches:
  only:
    master

# Build definition; language, deps, scripts
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements/dev.txt
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then tox -e py27; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then tox -e py34; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then tox -e py35; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then tox -e py36; fi
after_script:
  - pip install codecov
  - codecov
